### ISSUE TITLE
PHP Fatal error:  Uncaught MySQLReplication\Socket\SocketException

### ISSUE THREAD

**Issue by jasimaz** [krowinski/php-mysql-replication#88]
> Please provide the following details.

* *Operating System*: Linux Ubuntu 18.4
* *PHP Version*: 7.2
* *php-mysql-replication Version*: 7.0
* *mysql version (```SELECT VERSION();```):  MySQL 8.0

> Steps required to reproduce the problem.

1. Connecting to replica
2. Start consuming

> Expected Result.

The replication application should work continuously, it works for sometimes and throws error.

> Actual Result.

After running for few seconds, sometimes minutes it throws the following error;

PHP Fatal error:  Uncaught MySQLReplication\Socket\SocketException: Success in /var/apps/nxo-fetcher-new/src/MySQLReplication/Socket/Socket.php:65
Stack trace:
#0 /var/apps/nxo-fetcher-new/src/MySQLReplication/BinLog/BinLogSocketConnect.php(63): MySQLReplication\Socket\Socket->readFromSocket(1273)
#1 /var/apps/nxo-fetcher-new/src/MySQLReplication/Event/Event.php(57): MySQLReplication\BinLog\BinLogSocketConnect->getResponse()
#2 /var/apps/nxo-fetcher-new/src/MySQLReplication/MySQLReplicationFactory.php(130): MySQLReplication\Event\Event->consume()
#3 /var/apps/nxo-fetcher-new/src/MySQLReplication/MySQLReplicationFactory.php(116): MySQLReplication\MySQLReplicationFactory->consume()
#4 /var/apps/nxo-fetcher-new/app/stream.php(78): MySQLReplication\MySQLReplicationFactory->run()
#5 {main}
  thrown in /var/apps/nxo-fetcher-new/src/MySQLReplication/Socket/Socket.php on line 65

**Comment by jasimaz** [comment]
@krowinski, can you please provide me any update on this?
